
package View;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneDarkIJTheme;
import javax.swing.UIManager;
import Controller.CDashboard;
import javax.swing.table.TableModel;
/**
 *
 * @author Rajitha
 */
public class VDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form VDashBoard
     */
    public VDashBoard() {
        initComponents();
        btn_exit.setOpaque(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setBorderPainted(false);
        
        btn_log_out.setOpaque(false);
        btn_log_out.setContentAreaFilled(false);
        btn_log_out.setBorderPainted(false);
        
        
        CDashboard dash = new CDashboard();
        tbl_books.setModel((TableModel) dash.getBookData());
            
       
        
//        setExtendedState(VDashBoard.MAXIMIZED_BOTH);
//        this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_log_out = new javax.swing.JButton();
        btn_add_book = new javax.swing.JButton();
        btn_add_member = new javax.swing.JButton();
        btn_borrow_book = new javax.swing.JButton();
        btn_return_book1 = new javax.swing.JButton();
        btn_return_book = new javax.swing.JButton();
        btn_return_book2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_books = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lbl_issued_book = new javax.swing.JLabel();
        lbl_available_book = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_all_book = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 410));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 51));

        btn_exit.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 0, 0));
        btn_exit.setText("X");
        btn_exit.setBorderPainted(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIBM LIBRARY DASHBOARD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(btn_exit))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_exit)
                    .addComponent(jLabel1))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        btn_log_out.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btn_log_out.setForeground(new java.awt.Color(255, 255, 255));
        btn_log_out.setText("Log Out");
        btn_log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_outActionPerformed(evt);
            }
        });
        jPanel2.add(btn_log_out);
        btn_log_out.setBounds(0, 330, 100, 25);

        btn_add_book.setBackground(new java.awt.Color(153, 204, 255));
        btn_add_book.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btn_add_book.setForeground(new java.awt.Color(0, 0, 0));
        btn_add_book.setText("Add New Book");
        btn_add_book.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btn_add_book.setBorderPainted(false);
        jPanel2.add(btn_add_book);
        btn_add_book.setBounds(0, 0, 150, 45);

        btn_add_member.setBackground(new java.awt.Color(153, 204, 255));
        btn_add_member.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btn_add_member.setForeground(new java.awt.Color(0, 0, 0));
        btn_add_member.setText("Add Member");
        btn_add_member.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btn_add_member.setBorderPainted(false);
        jPanel2.add(btn_add_member);
        btn_add_member.setBounds(0, 50, 150, 45);

        btn_borrow_book.setBackground(new java.awt.Color(153, 204, 255));
        btn_borrow_book.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btn_borrow_book.setForeground(new java.awt.Color(0, 0, 0));
        btn_borrow_book.setText("Borrow Book");
        btn_borrow_book.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_borrow_book.setBorderPainted(false);
        jPanel2.add(btn_borrow_book);
        btn_borrow_book.setBounds(0, 100, 150, 45);

        btn_return_book1.setBackground(new java.awt.Color(153, 204, 255));
        btn_return_book1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btn_return_book1.setForeground(new java.awt.Color(0, 0, 0));
        btn_return_book1.setText("View Report");
        btn_return_book1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_return_book1.setBorderPainted(false);
        jPanel2.add(btn_return_book1);
        btn_return_book1.setBounds(0, 250, 150, 45);

        btn_return_book.setBackground(new java.awt.Color(153, 204, 255));
        btn_return_book.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btn_return_book.setForeground(new java.awt.Color(0, 0, 0));
        btn_return_book.setText("Return Book");
        btn_return_book.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_return_book.setBorderPainted(false);
        jPanel2.add(btn_return_book);
        btn_return_book.setBounds(0, 150, 150, 45);

        btn_return_book2.setBackground(new java.awt.Color(153, 204, 255));
        btn_return_book2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btn_return_book2.setForeground(new java.awt.Color(0, 0, 0));
        btn_return_book2.setText("Book History");
        btn_return_book2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_return_book2.setBorderPainted(false);
        jPanel2.add(btn_return_book2);
        btn_return_book2.setBounds(0, 200, 150, 45);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 370));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        tbl_books.setBackground(new java.awt.Color(215, 231, 255));
        tbl_books.setForeground(new java.awt.Color(0, 0, 0));
        tbl_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Author", "Availavility"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_books);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        lbl_issued_book.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lbl_issued_book.setForeground(new java.awt.Color(0, 0, 0));
        lbl_issued_book.setText("Issued Book Count = 13");

        lbl_available_book.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lbl_available_book.setForeground(new java.awt.Color(0, 0, 0));
        lbl_available_book.setText("Available Book Count = 12");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_issued_book)
                    .addComponent(lbl_available_book))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_available_book)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_issued_book))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        lbl_all_book.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lbl_all_book.setForeground(new java.awt.Color(0, 0, 0));
        lbl_all_book.setText("All Book Count = 15");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_all_book)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_all_book)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 650, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_outActionPerformed
        VLogin login = new VLogin();
        login.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btn_log_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatAtomOneDarkIJTheme());
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VDashBoard().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_book;
    private javax.swing.JButton btn_add_member;
    private javax.swing.JButton btn_borrow_book;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_log_out;
    private javax.swing.JButton btn_return_book;
    private javax.swing.JButton btn_return_book1;
    private javax.swing.JButton btn_return_book2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_all_book;
    private javax.swing.JLabel lbl_available_book;
    private javax.swing.JLabel lbl_issued_book;
    private javax.swing.JTable tbl_books;
    // End of variables declaration//GEN-END:variables
    
}
